# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inx_pb2 as inx__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class INXStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadNodeStatus = channel.unary_unary(
                '/inx.INX/ReadNodeStatus',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.ListenToNodeStatus = channel.unary_stream(
                '/inx.INX/ListenToNodeStatus',
                request_serializer=inx__pb2.NodeStatusRequest.SerializeToString,
                response_deserializer=inx__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.ReadNodeConfiguration = channel.unary_unary(
                '/inx.INX/ReadNodeConfiguration',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.NodeConfiguration.FromString,
                _registered_method=True)
        self.ReadProtocolParameters = channel.unary_unary(
                '/inx.INX/ReadProtocolParameters',
                request_serializer=inx__pb2.MilestoneRequest.SerializeToString,
                response_deserializer=inx__pb2.RawProtocolParameters.FromString,
                _registered_method=True)
        self.ReadMilestone = channel.unary_unary(
                '/inx.INX/ReadMilestone',
                request_serializer=inx__pb2.MilestoneRequest.SerializeToString,
                response_deserializer=inx__pb2.Milestone.FromString,
                _registered_method=True)
        self.ListenToLatestMilestones = channel.unary_stream(
                '/inx.INX/ListenToLatestMilestones',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.Milestone.FromString,
                _registered_method=True)
        self.ListenToConfirmedMilestones = channel.unary_stream(
                '/inx.INX/ListenToConfirmedMilestones',
                request_serializer=inx__pb2.MilestoneRangeRequest.SerializeToString,
                response_deserializer=inx__pb2.MilestoneAndProtocolParameters.FromString,
                _registered_method=True)
        self.ComputeWhiteFlag = channel.unary_unary(
                '/inx.INX/ComputeWhiteFlag',
                request_serializer=inx__pb2.WhiteFlagRequest.SerializeToString,
                response_deserializer=inx__pb2.WhiteFlagResponse.FromString,
                _registered_method=True)
        self.ReadMilestoneCone = channel.unary_stream(
                '/inx.INX/ReadMilestoneCone',
                request_serializer=inx__pb2.MilestoneRequest.SerializeToString,
                response_deserializer=inx__pb2.BlockWithMetadata.FromString,
                _registered_method=True)
        self.ReadMilestoneConeMetadata = channel.unary_stream(
                '/inx.INX/ReadMilestoneConeMetadata',
                request_serializer=inx__pb2.MilestoneRequest.SerializeToString,
                response_deserializer=inx__pb2.BlockMetadata.FromString,
                _registered_method=True)
        self.ListenToBlocks = channel.unary_stream(
                '/inx.INX/ListenToBlocks',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.Block.FromString,
                _registered_method=True)
        self.ListenToSolidBlocks = channel.unary_stream(
                '/inx.INX/ListenToSolidBlocks',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.BlockMetadata.FromString,
                _registered_method=True)
        self.ListenToReferencedBlocks = channel.unary_stream(
                '/inx.INX/ListenToReferencedBlocks',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.BlockMetadata.FromString,
                _registered_method=True)
        self.SubmitBlock = channel.unary_unary(
                '/inx.INX/SubmitBlock',
                request_serializer=inx__pb2.RawBlock.SerializeToString,
                response_deserializer=inx__pb2.BlockId.FromString,
                _registered_method=True)
        self.ReadBlock = channel.unary_unary(
                '/inx.INX/ReadBlock',
                request_serializer=inx__pb2.BlockId.SerializeToString,
                response_deserializer=inx__pb2.RawBlock.FromString,
                _registered_method=True)
        self.ReadBlockMetadata = channel.unary_unary(
                '/inx.INX/ReadBlockMetadata',
                request_serializer=inx__pb2.BlockId.SerializeToString,
                response_deserializer=inx__pb2.BlockMetadata.FromString,
                _registered_method=True)
        self.RequestTips = channel.unary_unary(
                '/inx.INX/RequestTips',
                request_serializer=inx__pb2.TipsRequest.SerializeToString,
                response_deserializer=inx__pb2.TipsResponse.FromString,
                _registered_method=True)
        self.ListenToTipsMetrics = channel.unary_stream(
                '/inx.INX/ListenToTipsMetrics',
                request_serializer=inx__pb2.TipsMetricRequest.SerializeToString,
                response_deserializer=inx__pb2.TipsMetric.FromString,
                _registered_method=True)
        self.ListenToTipScoreUpdates = channel.unary_stream(
                '/inx.INX/ListenToTipScoreUpdates',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.BlockMetadata.FromString,
                _registered_method=True)
        self.ReadUnspentOutputs = channel.unary_stream(
                '/inx.INX/ReadUnspentOutputs',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.UnspentOutput.FromString,
                _registered_method=True)
        self.ListenToLedgerUpdates = channel.unary_stream(
                '/inx.INX/ListenToLedgerUpdates',
                request_serializer=inx__pb2.MilestoneRangeRequest.SerializeToString,
                response_deserializer=inx__pb2.LedgerUpdate.FromString,
                _registered_method=True)
        self.ListenToTreasuryUpdates = channel.unary_stream(
                '/inx.INX/ListenToTreasuryUpdates',
                request_serializer=inx__pb2.MilestoneRangeRequest.SerializeToString,
                response_deserializer=inx__pb2.TreasuryUpdate.FromString,
                _registered_method=True)
        self.ReadOutput = channel.unary_unary(
                '/inx.INX/ReadOutput',
                request_serializer=inx__pb2.OutputId.SerializeToString,
                response_deserializer=inx__pb2.OutputResponse.FromString,
                _registered_method=True)
        self.ListenToMigrationReceipts = channel.unary_stream(
                '/inx.INX/ListenToMigrationReceipts',
                request_serializer=inx__pb2.NoParams.SerializeToString,
                response_deserializer=inx__pb2.RawReceipt.FromString,
                _registered_method=True)
        self.RegisterAPIRoute = channel.unary_unary(
                '/inx.INX/RegisterAPIRoute',
                request_serializer=inx__pb2.APIRouteRequest.SerializeToString,
                response_deserializer=inx__pb2.NoParams.FromString,
                _registered_method=True)
        self.UnregisterAPIRoute = channel.unary_unary(
                '/inx.INX/UnregisterAPIRoute',
                request_serializer=inx__pb2.APIRouteRequest.SerializeToString,
                response_deserializer=inx__pb2.NoParams.FromString,
                _registered_method=True)
        self.PerformAPIRequest = channel.unary_unary(
                '/inx.INX/PerformAPIRequest',
                request_serializer=inx__pb2.APIRequest.SerializeToString,
                response_deserializer=inx__pb2.APIResponse.FromString,
                _registered_method=True)


class INXServicer:
    """Missing associated documentation comment in .proto file."""

    def ReadNodeStatus(self, request, context):
        """Node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadNodeConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProtocolParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMilestone(self, request, context):
        """Milestones
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToLatestMilestones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToConfirmedMilestones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeWhiteFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMilestoneCone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMilestoneConeMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToBlocks(self, request, context):
        """Blocks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToSolidBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToReferencedBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlockMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTips(self, request, context):
        """Tips
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToTipsMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToTipScoreUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUnspentOutputs(self, request, context):
        """UTXO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToLedgerUpdates(self, request, context):
        """A stream that yields updates to the ledger. A `LedgerUpdate` represents a batch to be applied to the ledger.
        It first sends a `BEGIN`, then all the consumed outputs, then all the created outputs and finally an `END`.
        `BEGIN` and `END` will also be sent for milestones that did not mutate the ledger.
        The counts in the batch markers can be used to sanity check that everything arrived and to pre-allocate space if needed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToTreasuryUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenToMigrationReceipts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAPIRoute(self, request, context):
        """REST API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAPIRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformAPIRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_INXServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadNodeStatus,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.NodeStatus.SerializeToString,
            ),
            'ListenToNodeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToNodeStatus,
                    request_deserializer=inx__pb2.NodeStatusRequest.FromString,
                    response_serializer=inx__pb2.NodeStatus.SerializeToString,
            ),
            'ReadNodeConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadNodeConfiguration,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.NodeConfiguration.SerializeToString,
            ),
            'ReadProtocolParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProtocolParameters,
                    request_deserializer=inx__pb2.MilestoneRequest.FromString,
                    response_serializer=inx__pb2.RawProtocolParameters.SerializeToString,
            ),
            'ReadMilestone': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMilestone,
                    request_deserializer=inx__pb2.MilestoneRequest.FromString,
                    response_serializer=inx__pb2.Milestone.SerializeToString,
            ),
            'ListenToLatestMilestones': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToLatestMilestones,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.Milestone.SerializeToString,
            ),
            'ListenToConfirmedMilestones': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToConfirmedMilestones,
                    request_deserializer=inx__pb2.MilestoneRangeRequest.FromString,
                    response_serializer=inx__pb2.MilestoneAndProtocolParameters.SerializeToString,
            ),
            'ComputeWhiteFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeWhiteFlag,
                    request_deserializer=inx__pb2.WhiteFlagRequest.FromString,
                    response_serializer=inx__pb2.WhiteFlagResponse.SerializeToString,
            ),
            'ReadMilestoneCone': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadMilestoneCone,
                    request_deserializer=inx__pb2.MilestoneRequest.FromString,
                    response_serializer=inx__pb2.BlockWithMetadata.SerializeToString,
            ),
            'ReadMilestoneConeMetadata': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadMilestoneConeMetadata,
                    request_deserializer=inx__pb2.MilestoneRequest.FromString,
                    response_serializer=inx__pb2.BlockMetadata.SerializeToString,
            ),
            'ListenToBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToBlocks,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.Block.SerializeToString,
            ),
            'ListenToSolidBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToSolidBlocks,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.BlockMetadata.SerializeToString,
            ),
            'ListenToReferencedBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToReferencedBlocks,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.BlockMetadata.SerializeToString,
            ),
            'SubmitBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBlock,
                    request_deserializer=inx__pb2.RawBlock.FromString,
                    response_serializer=inx__pb2.BlockId.SerializeToString,
            ),
            'ReadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=inx__pb2.BlockId.FromString,
                    response_serializer=inx__pb2.RawBlock.SerializeToString,
            ),
            'ReadBlockMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlockMetadata,
                    request_deserializer=inx__pb2.BlockId.FromString,
                    response_serializer=inx__pb2.BlockMetadata.SerializeToString,
            ),
            'RequestTips': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTips,
                    request_deserializer=inx__pb2.TipsRequest.FromString,
                    response_serializer=inx__pb2.TipsResponse.SerializeToString,
            ),
            'ListenToTipsMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToTipsMetrics,
                    request_deserializer=inx__pb2.TipsMetricRequest.FromString,
                    response_serializer=inx__pb2.TipsMetric.SerializeToString,
            ),
            'ListenToTipScoreUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToTipScoreUpdates,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.BlockMetadata.SerializeToString,
            ),
            'ReadUnspentOutputs': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadUnspentOutputs,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.UnspentOutput.SerializeToString,
            ),
            'ListenToLedgerUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToLedgerUpdates,
                    request_deserializer=inx__pb2.MilestoneRangeRequest.FromString,
                    response_serializer=inx__pb2.LedgerUpdate.SerializeToString,
            ),
            'ListenToTreasuryUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToTreasuryUpdates,
                    request_deserializer=inx__pb2.MilestoneRangeRequest.FromString,
                    response_serializer=inx__pb2.TreasuryUpdate.SerializeToString,
            ),
            'ReadOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOutput,
                    request_deserializer=inx__pb2.OutputId.FromString,
                    response_serializer=inx__pb2.OutputResponse.SerializeToString,
            ),
            'ListenToMigrationReceipts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenToMigrationReceipts,
                    request_deserializer=inx__pb2.NoParams.FromString,
                    response_serializer=inx__pb2.RawReceipt.SerializeToString,
            ),
            'RegisterAPIRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAPIRoute,
                    request_deserializer=inx__pb2.APIRouteRequest.FromString,
                    response_serializer=inx__pb2.NoParams.SerializeToString,
            ),
            'UnregisterAPIRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAPIRoute,
                    request_deserializer=inx__pb2.APIRouteRequest.FromString,
                    response_serializer=inx__pb2.NoParams.SerializeToString,
            ),
            'PerformAPIRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformAPIRequest,
                    request_deserializer=inx__pb2.APIRequest.FromString,
                    response_serializer=inx__pb2.APIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inx.INX', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inx.INX', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class INX:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadNodeStatus',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToNodeStatus',
            inx__pb2.NodeStatusRequest.SerializeToString,
            inx__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadNodeConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadNodeConfiguration',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.NodeConfiguration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadProtocolParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadProtocolParameters',
            inx__pb2.MilestoneRequest.SerializeToString,
            inx__pb2.RawProtocolParameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMilestone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadMilestone',
            inx__pb2.MilestoneRequest.SerializeToString,
            inx__pb2.Milestone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToLatestMilestones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToLatestMilestones',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.Milestone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToConfirmedMilestones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToConfirmedMilestones',
            inx__pb2.MilestoneRangeRequest.SerializeToString,
            inx__pb2.MilestoneAndProtocolParameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeWhiteFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ComputeWhiteFlag',
            inx__pb2.WhiteFlagRequest.SerializeToString,
            inx__pb2.WhiteFlagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMilestoneCone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ReadMilestoneCone',
            inx__pb2.MilestoneRequest.SerializeToString,
            inx__pb2.BlockWithMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMilestoneConeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ReadMilestoneConeMetadata',
            inx__pb2.MilestoneRequest.SerializeToString,
            inx__pb2.BlockMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToBlocks',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToSolidBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToSolidBlocks',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.BlockMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToReferencedBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToReferencedBlocks',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.BlockMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/SubmitBlock',
            inx__pb2.RawBlock.SerializeToString,
            inx__pb2.BlockId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadBlock',
            inx__pb2.BlockId.SerializeToString,
            inx__pb2.RawBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlockMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadBlockMetadata',
            inx__pb2.BlockId.SerializeToString,
            inx__pb2.BlockMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/RequestTips',
            inx__pb2.TipsRequest.SerializeToString,
            inx__pb2.TipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToTipsMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToTipsMetrics',
            inx__pb2.TipsMetricRequest.SerializeToString,
            inx__pb2.TipsMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToTipScoreUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToTipScoreUpdates',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.BlockMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadUnspentOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ReadUnspentOutputs',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.UnspentOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToLedgerUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToLedgerUpdates',
            inx__pb2.MilestoneRangeRequest.SerializeToString,
            inx__pb2.LedgerUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToTreasuryUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToTreasuryUpdates',
            inx__pb2.MilestoneRangeRequest.SerializeToString,
            inx__pb2.TreasuryUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/ReadOutput',
            inx__pb2.OutputId.SerializeToString,
            inx__pb2.OutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenToMigrationReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inx.INX/ListenToMigrationReceipts',
            inx__pb2.NoParams.SerializeToString,
            inx__pb2.RawReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAPIRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/RegisterAPIRoute',
            inx__pb2.APIRouteRequest.SerializeToString,
            inx__pb2.NoParams.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAPIRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/UnregisterAPIRoute',
            inx__pb2.APIRouteRequest.SerializeToString,
            inx__pb2.NoParams.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformAPIRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inx.INX/PerformAPIRequest',
            inx__pb2.APIRequest.SerializeToString,
            inx__pb2.APIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
