{{- $c := dict "ctx" . "component" "relay" "values" .Values.relay }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "witness.componentName" $c }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "witness.labels" $c | nindent 4 }}
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - name: http
      port: {{ .Values.relay.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "witness.selectorLabels" $c | nindent 4 }}
