#!/usr/bin/env bash
# Generate the Python INX client stubs from the Stardust INX protocol definition.
#
# Fetches iotaledger/inx at a pinned commit of the `production` branch (the Stardust
# protocol that HORNET 2.x speaks; `develop` is IOTA 2.0) into vendor/inx and compiles
# proto/inx.proto into indexer/src/witness_indexer/inx_proto/. The output is committed;
# re-run only when bumping INX_REF.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

INX_REPO="https://github.com/iotaledger/inx.git"
INX_REF="${INX_REF:-4d08e4564d5465031fb3569864f3002ccd75732c}"  # production head, 2024-03-07
SRC="vendor/inx"
OUT="indexer/src/witness_indexer/inx_proto"

if [ ! -d "$SRC/.git" ]; then
  git clone --quiet --filter=blob:none --no-checkout "$INX_REPO" "$SRC"
fi
git -C "$SRC" fetch --quiet origin production
git -C "$SRC" checkout --quiet "$INX_REF"

mkdir -p "$OUT"
uv run python -m grpc_tools.protoc \
  -I "$SRC/proto" \
  --python_out="$OUT" \
  --pyi_out="$OUT" \
  --grpc_python_out="$OUT" \
  "$SRC/proto/inx.proto"

# protoc emits a top-level import; the stubs live inside a package.
sed -i 's/^import inx_pb2 as inx__pb2$/from . import inx_pb2 as inx__pb2/' "$OUT/inx_pb2_grpc.py"

cat > "$OUT/__init__.py" <<EOF
"""Python stubs for the INX gRPC interface (iotaledger/inx @ ${INX_REF:0:10}, production).

Generated by scripts/gen_inx.sh; do not edit by hand.
"""
EOF
echo "INX stubs written to $OUT"
